name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, export--4.0-firebase-final ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create config.js from environment variables
      run: |
        cat > config.js << EOF
        // Конфигурация Firebase из переменных окружения
        window.APP_CONFIG = {
          firebase: {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}"
          },
          app: {
            name: "Car Repair Tracker",
            version: "2.0.0",
            debug: false
          }
        };
        
        // Проверка конфигурации
        (function() {
          const config = window.APP_CONFIG.firebase;
          const requiredFields = ['apiKey', 'authDomain', 'projectId'];
          
          const missingFields = requiredFields.filter(field => 
            !config[field] || config[field].includes('${{') || config[field] === ''
          );
          
          if (missingFields.length > 0) {
            console.warn('Firebase configuration incomplete. Missing:', missingFields);
            console.warn('Please check GitHub Secrets configuration');
            
            document.addEventListener('DOMContentLoaded', () => {
              const warning = document.createElement('div');
              warning.style.cssText = \`
                position: fixed;
                top: 0;
                left: 0;
                right: 0;
                background: #f44336;
                color: white;
                padding: 10px;
                text-align: center;
                z-index: 10000;
                font-weight: bold;
              \`;
              warning.textContent = '⚠️ Ошибка конфигурации Firebase. Проверьте настройки GitHub Secrets.';
              document.body.appendChild(warning);
            });
          }
        })();
        EOF
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: true
