name: Deploy Static Site

on:
  push:
    branches: [ "main" ]

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Verify required files
      run: |
        if [ ! -f "index.html" ]; then
          echo "❌ Error: index.html not found!"
          exit 1
        fi
        if [ ! -f "styles.css" ]; then
          echo "❌ Error: styles.css not found!"
          exit 1
        fi
        if [ ! -f "script.js" ]; then
          echo "❌ Error: script.js not found!"
          exit 1
        fi
        echo "✅ All required files present"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./