name: Simple Deploy

on:
  push:
    branches: [ main, export--4.0-firebase-final ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create config.js
      run: |
        echo "Создаем config.js..."
        cat > config.js << 'EOF'
        // Конфигурация Firebase
        window.APP_CONFIG = {
          firebase: {
            apiKey: "${{ secrets.FIREBASE_API_KEY || 'DEMO_KEY' }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN || 'demo.firebaseapp.com' }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID || 'demo-project' }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET || 'demo.appspot.com' }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID || '123456789' }}",
            appId: "${{ secrets.FIREBASE_APP_ID || '1:123456789:web:demo' }}"
          },
          app: {
            name: "Car Repair Tracker",
            version: "2.0.0",
            debug: "${{ secrets.FIREBASE_API_KEY == '' }}"
          }
        };
        
        // Показываем статус конфигурации
        if ("${{ secrets.FIREBASE_API_KEY }}" == "") {
          document.addEventListener('DOMContentLoaded', () => {
            const warning = document.createElement('div');
            warning.style.cssText = \`
              position: fixed;
              top: 0;
              left: 0;
              right: 0;
              background: #ff9800;
              color: white;
              padding: 10px;
              text-align: center;
              z-index: 10000;
              font-weight: bold;
            \`;
            warning.textContent = '⚠️ Демо-режим. Добавьте GitHub Secrets для полноценной работы.';
            document.body.appendChild(warning);
          });
        }
        EOF
        
    - name: List files
      run: |
        echo "Содержимое директории:"
        ls -la
        echo ""
        echo "Содержимое config.js:"
        head -10 config.js
        
    - name: Deploy to GitHub Pages (Alternative)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: true 